# Generated by Django 5.0.2 on 2024-03-07 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Отображает название', max_length=200, verbose_name='Название(заголовок)')),
                ('slug', models.SlugField(help_text='Присвоение уникального адреса', verbose_name='Уникальный адрес')),
                ('description', models.TextField(help_text='Отображает описание группы', verbose_name='Описание')),
            ],
            options={
                'ordering': (('-pub_date',),),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='текст поста', verbose_name='текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Отображает дату публикации записи', verbose_name='Дата публикации')),
                ('autor', models.ForeignKey(help_text='Отображает имя автора', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(blank=True, help_text='Ваша группа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts_app.group', verbose_name='Группа')),
            ],
        ),
    ]
